version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:8000'
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tt2123
      MYSQL_DATABASE: asakatsu
    volumes:
      - ./db:/var/lib/mysql
      - ./etc/my.cnf:/etc/mysql/mysql.conf.d/my.cnf